timeout: 3600s # 1-hr
tags:
  - open-node-platform
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _GCP_REGION: ${GCP_REGION}
  _NODE_NAME: ${NODE_NAME}
  _CLUSTER_NAME: ${CLUSTER_NAME}
  _FULL_NODE_NAME: ${FULL_NODE_NAME}
options:
  substitution_option: 'ALLOW_LOOSE'
steps:
- name: "gcr.io/${_PROJECT_ID}/open-node-platform-installer"
  id: "add-validator-node"
  entrypoint: 'bash'
  args:
    - '-xe'
    - '-c'
    - |
      gcloud container clusters get-credentials ${_CLUSTER_NAME} --region ${_GCP_REGION}

      export FULL_NODE_SVC_NAME=$_FULL_NODE_NAME-service
      export FULL_NODE_IP=$(kubectl get svc $$FULL_NODE_SVC_NAME -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

      sed -i'' -e  "s/YOUR_NODE_NAME/${_NODE_NAME}/g" k8s/deployment-validator.yaml
      sed -i'' -e  "s/YOUR_FULL_NODE_IP/$${FULL_NODE_IP}/g" k8s/deployment-validator.yaml

      kubectl run -it temp-rpc -l app=temp-rpc --generator=run-pod/v1 --image=gcr.io/g-hash-community/polkadot-rpc-client:v1 \
      --env="ENDPOINT=ws://$$FULL_NODE_IP:9944"  \
      -- /usr/local/bin/node /workspace/getInfo.js

      sleep 10

      export PEER_ID=$(kubectl logs temp-rpc)

      sed -i'' -e  "s/YOUR_PEER_ID/$${PEER_ID}/g" k8s/deployment-validator.yaml

      sed -i'' -e  "s/YOUR_NODE_NAME/${_NODE_NAME}/g" k8s/pvc.yaml

      cat k8s/deployment-validator.yaml

      kubectl apply -f k8s/deployment-validator.yaml
      kubectl apply -f k8s/pvc.yaml

      kubectl delete pod temp-rpc
