timeout: 3600s # 1-hr
tags:
  - open-node-platform
steps:
- name: "gcr.io/${_PROJECT_ID}/open-node-platform-installer"
  id: "create-cluster"
  entrypoint: 'bash'
  args:
    - '-xe'
    - '-c'
    - |
      git clone -b dev https://github.com/Tenet-X/open-node.git

      sed -i'' -e  "s/PROJECT_ID/${_PROJECT_ID}/g" terraform.tfvars
      sed -i'' -e  "s/GCP_REGION/${_GCP_REGION}/g" terraform.tfvars
      sed -i'' -e  "s/CLUSTER_NAME/${_CLUSTER_NAME}/g" terraform.tfvars

      terraform init
      terraform plan -out=terraform.tfplan
      terraform apply -auto-approve terraform.tfplan
