timeout: 3600s
tags:
  - open-node-platform
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
options:
  substitution_option: 'ALLOW_LOOSE'
steps:
- name: "gcr.io/cloud-builders/gcloud"
  id: "build-install-image"
  entrypoint: bash
  args:
    - -c
    - |
      gcloud builds submit --config=build-image/cloudbuild.yaml --substitutions=_PROJECT_ID=${_PROJECT_ID}

- name: "gcr.io/${PROJECT_ID}/open-node-platform-installer"
  id: "create-cluster"
  entrypoint: 'bash'
  args:
    - '-xe'
    - '-c'
    - |
      eval "$(ssh-agent -s)"
      chmod 600 /pri_key
      ssh-add /pri_key

      git config --global user.email "charles_liuf@hotmail.com"
      git config --global user.name "Open Node Platform Installer"

      git clone git@github.com:Tenet-X/open-node.git
      cd open-node

      sed -i'' -e  "s/YOUR_PROJECT_ID/${_PROJECT_ID}/g" terraform.tfvars

      terraform init
      terraform plan -out=terraform.tfplan
      terraform apply -auto-approve terraform.tfplan

      gcloud container clusters get-credentials $(terraform output kubernetes_cluster_name) --region $(terraform output region)
      kubectl apply -f k8s/
