timeout: 3600s
tags:
  - open-node-platform
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _GCP_REGION: ${GCP_REGION}
  _NODE_NAME: ${NODE_NAME}
options:
  substitution_option: 'ALLOW_LOOSE'
steps:
- name: "gcr.io/cloud-builders/gcloud"
  id: "build-install-image"
  entrypoint: bash
  args:
    - -c
    - |
      gcloud builds submit --config=build-image/cloudbuild.yaml --substitutions=_PROJECT_ID=${_PROJECT_ID}

- name: "gcr.io/${PROJECT_ID}/open-node-platform-installer"
  id: "create-cluster"
  entrypoint: 'bash'
  args:
    - '-xe'
    - '-c'
    - |
      git clone -b dev https://github.com/Tenet-X/open-node.git

      sed -i'' -e  "s/PROJECT_ID/${_PROJECT_ID}/g" create-cluster/terraform.tfvars
      sed -i'' -e  "s/GCP_REGION/${_GCP_REGION}/g" create-cluster/terraform.tfvars
      sed -i'' -e  "s/NODE_NAME/${_NODE_NAME}/g" k8s/deployment.yaml
      sed -i'' -e  "s/NODE_NAME/${_NODE_NAME}/g" k8s/pvc.yaml

      cd create-cluster
      terraform init
      terraform plan -out=terraform.tfplan
      terraform apply -auto-approve terraform.tfplan

      cd ..
      gcloud container clusters get-credentials $(terraform output kubernetes_cluster_name) --region $(terraform output region)
      kubectl apply -f k8s/pvc.yaml
      kubectl apply -f k8s/deployment.yaml
  waitFor:
    - build-install-image
