timeout: 3600s # 1-hr
tags:
  - open-node-platform
steps:
- name: "gcr.io/${_PROJECT_ID}/open-node-platform-installer"
  id: "create-cluster"
  entrypoint: 'bash'
  args:
    - '-xe'
    - '-c'
    - |
      gcloud container clusters get-credentials ${_CLUSTER_NAME} --region ${_GCP_REGION}

      sed -i'' -e  "s/YOUR_NODE_NAME/${_NODE_NAME}/g" k8s/deployment.yaml
      sed -i'' -e  "s/YOUR_NODE_NAME/${_NODE_NAME}/g" k8s/pvc.yaml
      kubectl apply -f k8s/pvc.yaml
      kubectl apply -f k8s/deployment.yaml
